baseURL = "https://www.jacoblewallen.com/"
languageCode = "en-us"
title = "Jacob Lewallen"
# theme = "ezhil"
# theme = "hugo-book"
theme = "hugo-notepadium"

[params]
style = "auto"
dateFormat = "Monday, January 2, 2006"